// Generated by gencpp from file boris_manipulator/controlResponse.msg
// DO NOT EDIT!


#ifndef BORIS_MANIPULATOR_MESSAGE_CONTROLRESPONSE_H
#define BORIS_MANIPULATOR_MESSAGE_CONTROLRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace boris_manipulator
{
template <class ContainerAllocator>
struct controlResponse_
{
  typedef controlResponse_<ContainerAllocator> Type;

  controlResponse_()
    : connection_control(false)
    , distance_x(0.0)
    , distance_y(0.0)
    , distance_z(0.0)  {
    }
  controlResponse_(const ContainerAllocator& _alloc)
    : connection_control(false)
    , distance_x(0.0)
    , distance_y(0.0)
    , distance_z(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _connection_control_type;
  _connection_control_type connection_control;

   typedef double _distance_x_type;
  _distance_x_type distance_x;

   typedef double _distance_y_type;
  _distance_y_type distance_y;

   typedef double _distance_z_type;
  _distance_z_type distance_z;





  typedef boost::shared_ptr< ::boris_manipulator::controlResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::boris_manipulator::controlResponse_<ContainerAllocator> const> ConstPtr;

}; // struct controlResponse_

typedef ::boris_manipulator::controlResponse_<std::allocator<void> > controlResponse;

typedef boost::shared_ptr< ::boris_manipulator::controlResponse > controlResponsePtr;
typedef boost::shared_ptr< ::boris_manipulator::controlResponse const> controlResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::boris_manipulator::controlResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::boris_manipulator::controlResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::boris_manipulator::controlResponse_<ContainerAllocator1> & lhs, const ::boris_manipulator::controlResponse_<ContainerAllocator2> & rhs)
{
  return lhs.connection_control == rhs.connection_control &&
    lhs.distance_x == rhs.distance_x &&
    lhs.distance_y == rhs.distance_y &&
    lhs.distance_z == rhs.distance_z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::boris_manipulator::controlResponse_<ContainerAllocator1> & lhs, const ::boris_manipulator::controlResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace boris_manipulator

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::boris_manipulator::controlResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::boris_manipulator::controlResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::boris_manipulator::controlResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::boris_manipulator::controlResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::boris_manipulator::controlResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::boris_manipulator::controlResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::boris_manipulator::controlResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a2ac08319b695007e4197c737a10017b";
  }

  static const char* value(const ::boris_manipulator::controlResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa2ac08319b695007ULL;
  static const uint64_t static_value2 = 0xe4197c737a10017bULL;
};

template<class ContainerAllocator>
struct DataType< ::boris_manipulator::controlResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "boris_manipulator/controlResponse";
  }

  static const char* value(const ::boris_manipulator::controlResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::boris_manipulator::controlResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool connection_control\n"
"float64 distance_x\n"
"float64 distance_y\n"
"float64 distance_z\n"
;
  }

  static const char* value(const ::boris_manipulator::controlResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::boris_manipulator::controlResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.connection_control);
      stream.next(m.distance_x);
      stream.next(m.distance_y);
      stream.next(m.distance_z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct controlResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::boris_manipulator::controlResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::boris_manipulator::controlResponse_<ContainerAllocator>& v)
  {
    s << indent << "connection_control: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.connection_control);
    s << indent << "distance_x: ";
    Printer<double>::stream(s, indent + "  ", v.distance_x);
    s << indent << "distance_y: ";
    Printer<double>::stream(s, indent + "  ", v.distance_y);
    s << indent << "distance_z: ";
    Printer<double>::stream(s, indent + "  ", v.distance_z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BORIS_MANIPULATOR_MESSAGE_CONTROLRESPONSE_H
