// Generated by gencpp from file boris_manipulator/multiplyResponse.msg
// DO NOT EDIT!


#ifndef BORIS_MANIPULATOR_MESSAGE_MULTIPLYRESPONSE_H
#define BORIS_MANIPULATOR_MESSAGE_MULTIPLYRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace boris_manipulator
{
template <class ContainerAllocator>
struct multiplyResponse_
{
  typedef multiplyResponse_<ContainerAllocator> Type;

  multiplyResponse_()
    : result(0)  {
    }
  multiplyResponse_(const ContainerAllocator& _alloc)
    : result(0)  {
  (void)_alloc;
    }



   typedef int32_t _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::boris_manipulator::multiplyResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::boris_manipulator::multiplyResponse_<ContainerAllocator> const> ConstPtr;

}; // struct multiplyResponse_

typedef ::boris_manipulator::multiplyResponse_<std::allocator<void> > multiplyResponse;

typedef boost::shared_ptr< ::boris_manipulator::multiplyResponse > multiplyResponsePtr;
typedef boost::shared_ptr< ::boris_manipulator::multiplyResponse const> multiplyResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::boris_manipulator::multiplyResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::boris_manipulator::multiplyResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::boris_manipulator::multiplyResponse_<ContainerAllocator1> & lhs, const ::boris_manipulator::multiplyResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::boris_manipulator::multiplyResponse_<ContainerAllocator1> & lhs, const ::boris_manipulator::multiplyResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace boris_manipulator

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::boris_manipulator::multiplyResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::boris_manipulator::multiplyResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::boris_manipulator::multiplyResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::boris_manipulator::multiplyResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::boris_manipulator::multiplyResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::boris_manipulator::multiplyResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::boris_manipulator::multiplyResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "034a8e20d6a306665e3a5b340fab3f09";
  }

  static const char* value(const ::boris_manipulator::multiplyResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x034a8e20d6a30666ULL;
  static const uint64_t static_value2 = 0x5e3a5b340fab3f09ULL;
};

template<class ContainerAllocator>
struct DataType< ::boris_manipulator::multiplyResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "boris_manipulator/multiplyResponse";
  }

  static const char* value(const ::boris_manipulator::multiplyResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::boris_manipulator::multiplyResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 result\n"
;
  }

  static const char* value(const ::boris_manipulator::multiplyResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::boris_manipulator::multiplyResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct multiplyResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::boris_manipulator::multiplyResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::boris_manipulator::multiplyResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<int32_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BORIS_MANIPULATOR_MESSAGE_MULTIPLYRESPONSE_H
